# Generated by Django 5.2.9 on 2025-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(max_length=5)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('dtentrada', models.DateTimeField(auto_now_add=True)),
                ('dtvalidade', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
