# Generated by Django 5.2.9 on 2025-12-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemestoque',
            old_name='dtentrada',
            new_name='dataentrada',
        ),
        migrations.RenameField(
            model_name='itemestoque',
            old_name='dtvalidade',
            new_name='datavalidade',
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='categoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='donoprenome',
            field=models.CharField(default='Sandeison', max_length=32),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='donosobrenome',
            field=models.CharField(default='Fernandes', max_length=32),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='localizacao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
