# Generated by Django 5.2.9 on 2025-12-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_rename_dtentrada_itemestoque_dataentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemestoque',
            name='categoria',
            field=models.CharField(default='Geral', max_length=30),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='localizacao',
            field=models.CharField(default='Armazém A', max_length=30),
        ),
    ]
