# Generated by Django 5.2.9 on 2025-12-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_itemestoque_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='datavalidade',
        ),
    ]
